general:
  label: 基础设置
  items:
    cover:
      name: cover_image
      label: 首页封面图
      type: attachment
    links_cover:
      name: links_cover
      label: 友情链接封面图
      type: attachment
    archives_cover:
      name: archives_cover
      label: 归档封面图
      type: attachment
    code_pretty:
      name: code_pretty
      label: 文章代码高亮主题
      type: select
      default: Default
      options:
        - value: default
          label: Default
        - value: coy
          label: Coy
        - value: dark
          label: Dark
        - value: okaidia
          label: Okaidia
        - value: solarized-light
          label: Solarized Light
        - value: tomorrow-night
          label: Tomorrow Night
        - value: twilight
          label: Twilight
    code_line_numbers:
      name: code_line_numbers
      label: 代码显示行号
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
#sns:
#  label: 社交设置
#  items:
#    rss:
#      name: rss
#      label: RSS
#      type: radio
#      data-type: bool
#      default: true
#      options:
#        - value: true
#          label: 开启
#        - value: false
#          label: 关闭
#    twitter:
#      name: twitter
#      label: Twitter
#      type: text
#      placeholder: '只需填入 Twitter 用户名即可'
#    facebook:
#      name: facebook
#      label: Facebook
#      type: text
#      placeholder: '只需填入 Facebook 用户名即可'
#    instagram:
#      name: instagram
#      label: Instagram
#      type: text
#      placeholder: '只需填入 Instagram 用户名即可'
#    weibo:
#      name: weibo
#      label: 微博
#      type: text
#      placeholder: '只需填入微博 Id 即可'
#    email:
#      name: email
#      label: Email
#      type: text
#      placeholder: '邮箱地址'
#    telegram:
#      name: telegram
#      label: Telegram
#      type: text
#      placeholder: '只需填入 Telegram Id 即可'
#    github:
#      name: github
#      label: Github
#      type: text
#      placeholder: '只需填入 Github 用户名即可'